### ISSUE TITLE
Is there..

### ISSUE THREAD

**Issue by MattM9** [pierr3/vSMR#1]
A way to stop the squawk and aircraft type rotating and flashing? e.g. in your datalink example video.

Thanks

**Comment by MattM9** [comment]
Hello again,

Is there also a way to edit the tag content? e.g. to remove aircraft type and just have Stand number for inbounds?

**Comment by pierr3** [comment]
I'll add the possibility to toggle on/off the squawk warning. No there is no way to edit the tag content, but i'll see about changing the current layout to make the single line tag more realistic.

**Comment by MattM9** [comment]
Hi Pierre,

Thanks for the reply... There is somewhere on the Vatsim UK forum is a
picture of the tags in the UK. I'll try and find a link for you.

Thank you and great job!

Matt

On Saturday, April 11, 2015, Pierre Ferran notifications@github.com wrote:

> I'll add the possibility to toggle on/off the squawk warning. No there is
> no way to edit the tag content, but i'll see about changing the current
> layout to make the single line tag more realistic.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pierr3/vSMR/issues/1#issuecomment-91837121.

## 

Matt Middleton
07962-130470

**Comment by sw104** [comment]
Sorry to butt in!

Here is a link to the tags at Heathrow: http://community.vatsim-uk.co.uk/topic/29397-image-heathrow-smr-tags/?hl=buff#entry263760

Here is a link to how the tags are correlated to each aircraft (if you want to implement this): http://community.vatsim-uk.co.uk/topic/28399-images-gatwick-smr-photos/

**Comment by pierr3** [comment]
@samwhite1 Thanks for that, and yes i'll be interested in introducing realistic correlation on the ground.

**Comment by pierr3** [comment]
Aircraft type and squawk errors can be hidden in 77bad83219eab39084d93ace2a1ae60391862f0a, also squawk error doesn't flash anymore.

**Comment by pierr3** [comment]
Op's requests implemented in 59b9214a406023a1aebb40bccf977e99633ccda1
