### ISSUE TITLE
Double clicking to select aircraft

### ISSUE THREAD

**Issue by arcticash** [pierr3/vSMR#10]
I'm not sure how realistic this is but it was very useful when controlling large numbers of a/c at Gatwick!

Previously once an aircraft made contact with ground we where able to double click on an aircraft callsign and that would "Select" the aircraft so that it was highlighted when the mouse is hovered over the departure list, is this something you would look at implementing with this plugin as that feature seems to have stopped working since installing vSMR?

Thanks
Ash

**Comment by pierr3** [comment]
I see what you mean, i'm affraid EuroScope won't allow me to do that :confused:
