### ISSUE TITLE
Unable to get aircraft to show on SMR

### ISSUE THREAD

**Issue by Genau6502** [pierr3/vSMR#107]
Hello,

Followed the wiki instructions about 10 times for converting existing ASRs and for creating new ones: I can't get aircraft to show up on the SMR. I've checked through everything I can find, ensuring that the maximum altitude is well above the aerodrome, changing the screen type, making sure that the correct ICAO is set, everything. Still can't get tags to show - any ideas?

![image](https://user-images.githubusercontent.com/66269211/233854352-32726bd5-c2ca-4c7c-a255-5e2a7adb5c34.png)
![image](https://user-images.githubusercontent.com/66269211/233854380-20143100-c182-4b17-a11b-04422339b772.png)

All the usual lists are populated with aircraft that show up on radar, just not on SMR
Any suggestions?

**Comment by kusterjs** [comment]
> All the usual lists are populated with aircraft that show up on radar, just not on SMR
> Any suggestions?

Just to make sure, you followed this guide? https://github.com/pierr3/vSMR/wiki/Setting-up-the-ground-radar
Can you include your ASR file?

**Comment by Genau6502** [comment]
https://drive.google.com/file/d/1CLEoL2SLsKyybswsQxFP2QriUQe-nDD2/view?usp=sharing for the ASR

Yes, I've followed the wiki instructions, many times. Still no luck

**Comment by kusterjs** [comment]
The one I used is set to Radar simulation mode. Maybe this helps? I think the ground mode is not really needed as the drawing is added by the plugin then.

**Comment by Genau6502** [comment]
Tried all the simulation modes, none of them make aircraft appear

**Comment by Genau6502** [comment]
Found a fix, sector file problems, thanks!
