### ISSUE TITLE
Runway Closed and Magnetic Variation

### ISSUE THREAD

**Issue by sw104** [pierr3/vSMR#11]
At Stansted the red runway closed outline appears to be offset by a few degrees - this is the same no matter if I select 04 or 22 as closed:
![vsmr runways](https://cloud.githubusercontent.com/assets/8680919/8513111/fb03caae-2355-11e5-89c5-a4ce1b5fe0d8.PNG)

**Comment by pierr3** [comment]
I think that may be a EuroScope bug, will try something.

**Comment by sw104** [comment]
Thanks!

**Comment by pierr3** [comment]
The next version should have an option to manually define the runways, that might fix the bug, otherwise, it's a EuroScope bug.
