### ISSUE TITLE
Stanby aircrafts

### ISSUE THREAD

**Issue by Bartek-M** [pierr3/vSMR#115]
Hello,
this plugin is great, but I'm missing one feature. Could you add an option for pro_mode to hide aircraft TAGs with standby transponder. How else do we know that certain aircraft is squawking the correct code, when his transponder is not transmitting anything?

Thank you.

**Comment by Epse** [comment]
Feel free to pull code for that from our belux-vsmr version, it's quite robust. At this point the versions have diverged too much to put direct pull requests against this, but I am all for sharing
