### ISSUE TITLE
Strange Primary Targets

### ISSUE THREAD

**Issue by sw104** [pierr3/vSMR#12]
I was just wondering if the primary targets are supposed to look like this:
![vsmr targets](https://cloud.githubusercontent.com/assets/8680919/8513476/5f44ed14-2364-11e5-9154-091ec6580079.PNG)

**Comment by pierr3** [comment]
Yea that's also due to the magnetic variation, try it without and you'll see.

**Comment by pierr3** [comment]
I made some checks, this is due to the mag var in EuroScope, it wasn't meant to be used with big magnetic vars, hence why it does funny stuff :s
