### ISSUE TITLE
Professional Mode Correlation

### ISSUE THREAD

**Issue by matthewmoy** [pierr3/vSMR#13]
Hi,

In the next version of vSMR is it possible to add Professional Mode Correlation ? A bit like Ground without S-mode Radar.

I know in the UK, we can only see the blips of each aircraft when they are not correlated and identified on the ground, and once an aircraft has been correlated and assigned a Squawk code we can see him on the radar screen with his C/S. Do you think it could be possible to implement it ? I could give you more information if you want.

And a bug I've found: If an aircraft connect with only text (tag= /t), but he is by voice, when I change it to voice or receive in ES, the tag stay with /t. But, if an aircraft connect with voice and he is in text, I change it in Euroscope and the tag change. It's only when the pilot connect with text only. 

Thanks,

**Comment by pierr3** [comment]
No worries, the pro mode is high on the to-do list.

**Comment by matthewmoy** [comment]
Oh ok, cool. With the blips only available when not correlated ?

**Comment by pierr3** [comment]
The behaviour will be as follows: An aircraft logs in with a flight plan, only the primary blips appears on the gate. When the aircraft request clearance, he will be assign a squawk by the controller, when he squawks that code, he will automatically be correlated. If an uncorrelated aircraft starts to move with a speed > 3kts, his primary blip will be followed by a tag, containing only the system ID of the aircraft, it will be up for the controller to manually correlate the blip or not.

**Comment by matthewmoy** [comment]
Oh ok, pretty cool :) Any release date for the beta ?

**Comment by pierr3** [comment]
First of all I need to start working on it :stuck_out_tongue_winking_eye:

**Comment by matthewmoy** [comment]
Oh ok, Haha :D

**Comment by pierr3** [comment]
Almost done!
![](https://i.imgur.com/stBkIzb.png)

**Comment by matthewmoy** [comment]
Nice :-) What is the "T:" ?

**Comment by pierr3** [comment]
"Target" then the Target ID, the tag can be customized like the other ones.

**Comment by matthewmoy** [comment]
Oh cool, really excited to have it :) It will be perfect with my plugin for Manchester !

**Comment by TheoBearman** [comment]
What plugin is that?

**Comment by matthewmoy** [comment]
Is this an issue or not ?

Having no space between the text and the background blue ?

http://i.imgur.com/9THhmEc.png

**Comment by pierr3** [comment]
Not an issue no, also curious, what Manchester plugin? :stuck_out_tongue:

**Comment by matthewmoy** [comment]
Oh ok, is there a way to add a little space in the settings file ? Erm .. Do you have a e-mail where I could contact you about it ? Sorry I don't really want to say it here, because only a few people now the existence of this project. Could I contact you via e-mail ? ;-)

**Comment by pierr3** [comment]
pierre@ferran.io, and no, no such setting :s. For info, the real world has no padding.

**Comment by matthewmoy** [comment]
E-mail sent ;)

**Comment by pierr3** [comment]
All of that has been implemented in the private beta.

**Comment by matthewmoy** [comment]
Any update/plan to release this as a public beta ? ☺️
