### ISSUE TITLE
Extended Centerline Length Setting Spelling

### ISSUE THREAD

**Issue by sw104** [pierr3/vSMR#15]
Hi,

Once again thank you so much for developing such an amazing plugin and sorry for the lack of progress with the wiki - I have been away for the last month!

Would it be possible to change the `extended_lines_lenght` setting under the `approach_insets` section of the .json settings file to: `extended_lines_length`?

Thanks again,
Sam

**Comment by pierr3** [comment]
Yep, sure!

**Comment by sw104** [comment]
Thanks! :-)
