### ISSUE TITLE
Accept Pilot Squawk

### ISSUE THREAD

**Issue by sw104** [pierr3/vSMR#16]
Would it be possible to add an 'Accept pilot squawk' option to the vSMR pro mode, similar to this same function in the default EuroScope professional modes?

E.g. If an aircraft has no assigned squawk and is not squawking a code on a user-editable list of non-discrete squawks in the .json settings file - the same idea as the 'Do not auto correlate' squawks on the EuroScope general settings page - then the aircraft will be correlated correctly to its flightplan. This should stop ground/tower from having to assign squawks un-necessarily to inbound aircraft when there is no higher control online.

**Comment by pierr3** [comment]
Will add that, didn't think about that eventuality.

**Comment by sw104** [comment]
Thanks!
