### ISSUE TITLE
Release v1.2.0-beta.1 wrong link

### ISSUE THREAD

**Issue by theomessin** [pierr3/vSMR#17]
Tag items correct link:

https://github.com/pierr3/vSMR/blob/master/vSMR/SMRRadar.cpp#L1433-L1445

**Comment by pierr3** [comment]
Indeed, gonna write the proper list once is done as this link basically changes everytime I update the code

**Comment by theomessin** [comment]
You can use this one then...
https://github.com/pierr3/vSMR/blob/v1.2.0-beta.1/vSMR/SMRRadar.cpp#L1195-L1209
It is tag specific so code edits won't affect it... 

Or you can just reference the wiki here:
https://github.com/pierr3/vSMR/wiki/Editing-the-Plugin-Settings-(.json-file)#available-tag-items
