### ISSUE TITLE
Active profile font not working

### ISSUE THREAD

**Issue by theomessin** [pierr3/vSMR#18]
Tried to find the error in the code. All I can guess is that the active profile hasn't initialized when getting the active font, therefore everything is rendered using the font from the default profile (ie. font family sizes and weight). That is, profile specific font settings are simply ignored...

**Comment by pierr3** [comment]
Yep, I think I fixed it in the latest closed beta, will make sure and let you know.

**Comment by pierr3** [comment]
Fixed in f0861077f8f41a4dcc4695f6e3fe474f1567394b
