### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheoBearman** [pierr3/vSMR#2]
Make aircraft symbol trigger ground status dialogue on left click.

Discussed on Skype. Including the possibility of a 'reset' button which would help deal with the 'Push' button being accidentally pressed.

**Comment by pierr3** [comment]
After extensive testing, it's unfortunately technically not possible :confused: I'll ask Gergely if he would be able to add that feature in the next version.

**Comment by TheoBearman** [comment]
Can you ask Gergely if he can put a 'reset' option in the ground status dialogue too then?

**Comment by pierr3** [comment]
I will.
