### ISSUE TITLE
showing SID on departure tag

### ISSUE THREAD

**Issue by ghost** [pierr3/vSMR#20]
Hi, looks like this is planned but not yet implemented as I see it in the documentation. Is this still on the to do list as it would be a big help for me!

**Comment by pierr3** [comment]
Indeed it seems that the SID tag item is not the public beta, it's in the private though, i'll see if I can publish that one.

**Comment by ghost** [comment]
Awesome thank you !

**Comment by ghost** [comment]
Happy to test a private build if you need testers. My C++ knowledge is particularly poor!

**Comment by ghost** [comment]
Just wondering if you got anywhere with this?

**Comment by pierr3** [comment]
Give me the email of your trello account if you have one, or just an email. I'll all you to the beta board ;) Send it to pierre - at - ferran - dot - io
