### ISSUE TITLE
Outbound background colors.

### ISSUE THREAD

**Issue by erikwachters** [pierr3/vSMR#22]
Hello,

Is it possible to integrate a feature where you can define two background colors for departing traffic.
In our (EBBR) system we have a yellow color for the outbound traffic using certain SID's to the east and others are cyan. 
Maybe a section in the .json file where you can define the SID's and there corresponding color?

Thanks,

Erik

**Comment by arcticash** [comment]
This would be a brilliant idea and I can see it being useful at Gatwick also :)

**Comment by pierr3** [comment]
Shouldn't be too hard to implement, i'll consider it, but don't expect it any time soon.

**Comment by ghost** [comment]
Any update on this Pierre?

Merci,
Chriss

**Comment by pierr3** [comment]
Sorry for the late reply, but no progress so far. Current focus is just on maintaining compatibility.

**Comment by MatisseBE** [comment]
Almost a year later now, any updates on the suggestion? :)

Thanks,

Matisse Van Wezer

**Comment by pierr3** [comment]
Very sorry to say I have not done any work on this, and do not plan to in the near future.

**Comment by keanucz** [comment]
Sounds interesting, I could probably have a go

**Comment by keanucz** [comment]
I've managed to get this working and I will submit a PR for this soon and a couple of other improvements
