### ISSUE TITLE
TAG issues 

### ISSUE THREAD

**Issue by Koploper9** [pierr3/vSMR#24]
Hello

I've installed the latest version of the plugin and I've followed the instructions on the wiki but I'm still experiencing some issues that I didn't have in the beta version

-When I click a TAG line, for example the callsign, nothing happens, I can't open the handoff menu, the FP etc.
-I can't move the TAG's in the approach window.

I have added my system specs.
[specs.txt](https://github.com/pierr3/vSMR/files/428417/specs.txt)

Thanking you in advance

Simon

**Comment by sw104** [comment]
Hi Simon,

With regard to the actions when you click the tag items, I believe that these were changed so that you have to right-click the items instead of left-clicking them.

I'll leave the other points for Pierre to answer! ;-)

**Comment by Koploper9** [comment]
Hi

Unfortunately I already knew en tried that :-(. But thanks for the answer anyhow :-)

**Comment by kusterjs** [comment]
To change the position of the label in the approach window, click on the target and it will switch to the next position. There is no option to drag the label freely. This is a solution used in different real life systems and makes it quite easy for controllers to organize their labels.

**Comment by pierr3** [comment]
I probably messed up calculating the bounding box for the click items when I changed the tag drawing system, sorry about that

**Comment by Koploper9** [comment]
@kusterjs Thanks, that works!
@pierr3 Ok, once you are used to it, it isn't a big deal.

**Comment by LB767** [comment]
I think I may have found the problem, I need to test it live on ES to see if that's really it.
The text click spots seem do be drawn before the actual tag click spot, which ends up being on top of everything.
Basically it does `AddScreenObject(TagClickableMap[element], ...` before `AddScreenObject(DRAWING_TAG, ...`
The order was inverted before the tag refactoring update.

**Comment by pierr3** [comment]
@LB767 Can you test your fix, and if it works could you create a pull request?

**Comment by LB767** [comment]
@pierr3 Oh I had already tested it and it was indeed that. You already merged it :)
Though I think there might still be something odd with the click and drag of tags sometimes, not exactly sure what.

**Comment by pierr3** [comment]
@LB767 My bad, my memory failed me, I'll recompile asap and post the update.

**Comment by pierr3** [comment]
The nightly build is out, could anyone check if Lionel fixed it?
https://ci.appveyor.com/api/projects/pierr3/vSMR/artifacts/vSMR-nightly.zip

**Comment by LB767** [comment]
I just noticed there's still a bug somewhere as I can't click&drag the tag if it's uncorrelated. Will have to look into that...

**Comment by pierr3** [comment]
Fixed thanks to @LB767 in #29
