### ISSUE TITLE
Impossible to use vSMR due to a Microsoft Visual Studio 14.0 bug

### ISSUE THREAD

**Issue by matthewmoy** [pierr3/vSMR#28]
Each time I start EuroScope, it creates me a bug for vSMR.dll about Microsoft Visual Studio 14.0 bug line 102 & 103.

Any way of fixing it? See the attached pictures.
![euroscope_2017-02-01_20-56-08](https://cloud.githubusercontent.com/assets/13717304/22525916/29f74426-e8c1-11e6-9764-75fb239288a6.png)
![euroscope_2017-02-01_20-56-23](https://cloud.githubusercontent.com/assets/13717304/22525917/29fed178-e8c1-11e6-8988-253e2bd3657b.png)

N.B: This only happens with the night build.

**Comment by pierr3** [comment]
Which version of vSMR are you using ?

**Comment by matthewmoy** [comment]
The Nightly build.

**Comment by pierr3** [comment]
Try to redownload the nightly build, and see if that works, if it doesn't can you try starting up the log by typing .smr log in the chat (Needs to be typed on an SMR radar screen) and giving me the last lines of the log file?

**Comment by pierr3** [comment]
Also, make sure that the ICAO_Airlines.txt file is in the same folder as the vSMR.dll, as well as the latest .json file

**Comment by matthewmoy** [comment]
Brilliant, it is now working.
