### ISSUE TITLE
Arrivals Stand

### ISSUE THREAD

**Issue by sw104** [pierr3/vSMR#3]
Hi,

Would it be possible for the arrivals stand to also be read from the 'assigned speed' field in EuroScope as well as the scratchpad, as lots of people put the arrivals stand in here instead of the scratchpad, and it is also standard procedure to do this at Heathow?

Thank you very much,
Sam

**Comment by pierr3** [comment]
I'll consider it.

**Comment by sw104** [comment]
Thanks!

**Comment by pierr3** [comment]
Option has been added in 22d309cb4de65bf8e215d790fb9a59aee6f3d6d4
