### ISSUE TITLE
Feature Suggestion: Automatically reply "UNABLE" to pilots requesting CPDLC-Logon

### ISSUE THREAD

**Issue by mkreu** [pierr3/vSMR#30]
Hi,

While manning delivery in EDDM during this years CTP, I went into a small problem using the vSMR PDC feature: Many pilots erroneously tried to logon to my callsign instead of requesting the PDC without logon.   Although I told them to request PDC without logon, they were not able to receive my clearance as the hoppie pilot client apparently ignores other messages while waiting for an "ACCEPTED" or "UNABLE" response to its logon request.

Therefore i suggest adding a function to automatically reject logon requests. (or a manual possibility to do so)

Regards, 
Michael

**Comment by pierr3** [comment]
Good idea

**Comment by keanucz** [comment]
Should an option for this go in the JSON config or should it go somewhere else? @pierr3

**Comment by kusterjs** [comment]
This should be implemented by default to overcome a System Design issue of Hoppie. So no option required for the user to able/disable.

**Comment by keanucz** [comment]
Whoops, forgot to remove this from the PR body; this isn't fixed yet @pierr3

**Comment by DrFreas** [comment]
I made a thing regarding this in pull request #58.
