### ISSUE TITLE
"use_departure_arrival_coloring"

### ISSUE THREAD

**Issue by LB767** [pierr3/vSMR#33]
Do you remember whether this parameter was implemented or not?

It doesn't seem to work and I can't find it in the code.
(Just so I don't start coding something that I stupidly missed :P)

**Comment by pierr3** [comment]
In my head it was fully implemented, but I think I accidentally removed the feature when I refactored the tag drawing, it should be around [here](https://github.com/pierr3/vSMR/blob/e1013e9150a9dc27a142b6765bb487a5aefa853c/vSMR/SMRRadar.cpp#L2175) but I can't find it either, go for it!
