### ISSUE TITLE
Font size on the aircrafts tag (first row)

### ISSUE THREAD

**Issue by bozibence** [pierr3/vSMR#37]
Hello! My question is that is it possible to increase the font size of the first row on the tag. For example: the first line on the tag is the callsign and it is bigger than the second row. Thank you in advance.

**Comment by pierr3** [comment]
Hi, that is not possible with the current version of vSMR.

**Comment by bozibence** [comment]
Hello! In the last conversation you said that it is not possible with the current version but you had some updates ever since. Maybe do you plan to do it in the future? :) I am asking because in the real version (in Hungary) the first row is larger than the other. Here it is a picture from it: 
[https://i.snag.gy/OERW79.jpg](url)
Thank you very very much for your answer and your help! 👍 :)
