### ISSUE TITLE
Plugin not showing some of the airports in Iran vACC

### ISSUE THREAD

**Issue by ep3mhb** [pierr3/vSMR#38]
Hello,

I made a layout for Tabriz (OITT) and also for IKA (OIIE) and Mehrabad (OIII).

Plugins showing aircraft in OIIE and OIII but not showing in OITT.

Same happened in Pakistan for OPIS.

Someone told us that maybe those airports are not included in vSMR database.

Thanks for your kind attention.

Regards

**Comment by mic12130** [comment]
The Plug-In looks don't have such a database of airports, it based on data in sector file. I believe that this issue caused by the filter altitude in vSMR profile.

Try these steps:
- Open vSMR_Profiles.json
- Change "hide_above_alt" to a higher altitude than the highest airports in the sector file
- Type ".smr reload" in vSMR asr and enter (Or restart the EuroScope)

**Comment by pierr3** [comment]
@mic12130 Thank you for this, it is most probably the answer. Please also ensure you correctly set the active airport in the top left of the vSMR menu bar. This issue will be closed unless @ep3mhb still faces an issue, please let me know.

**Comment by ep3mhb** [comment]
Dear Pierr,

Yes the issue is solved after applying the correct area altitude into the
file.

-- 
Mohammad H. Bahrololoum
Sent with Airmail

On November 14, 2018 at 9:50:47 PM, Pierre Ferran (notifications@github.com)
wrote:

@mic12130 <https://github.com/mic12130> Thank you for this, it is most
probably the answer. Please also ensure you correctly set the active
airport in the top left of the vSMR menu bar. This issue will be closed
unless @ep3mhb <https://github.com/ep3mhb> still faces an issue, please let
me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pierr3/vSMR/issues/38#issuecomment-438755149>, or mute
the thread
