### ISSUE TITLE
SMR cursor is not loaded

### ISSUE THREAD

**Issue by mic12130** [pierr3/vSMR#39]
Hi,

In the latest 1.4.0 release, It's looks like an issue that the SMR cursor in previous version is replaced by the default Windows cursor.

After checking the commits since 1.3,3, I supposed it caused by a "test" in commit 5e74214. Then I tried to revert the WindowProc callback and some related variables which were removed in 5e74214 (https://github.com/mic12130/vSMR/commit/109112563a4b60047b36c9d2f8275c584fd1f37b), The cursor is loaded as before.

**Comment by pierr3** [comment]
Guess I really should start testing before releasing. I see where the problem is, could you create a pull request with your fix ? I'll be sure to merge and re-release.

**Comment by pierr3** [comment]
Thanks for your help, I'll do another release asap.
