### ISSUE TITLE
Aircraft Direction During Pushback

### ISSUE THREAD

**Issue by sw104** [pierr3/vSMR#4]
Hello,

When aircraft are pushing back their polygon points in the direction of pushback instead of the actual direction the aircraft is facing. Would it be possible to draw the primary target polygon based on the aircraft's heading?

Thanks,
Sam

P.S. Sorry for the premature posting.

**Comment by pierr3** [comment]
Fixed in 77bad83219eab39084d93ace2a1ae60391862f0a.
