### ISSUE TITLE
Allow multiple airports with one ASR

### ISSUE THREAD

**Issue by luke11brown** [pierr3/vSMR#41]
Love using vSMR, however, when covering an area position, e.g. LON_CTR with many airfields top down, I have to use only 1 or 2 ASRs, switching between airfields using .center[ICAO] to display the airfield I want to see. To then get vSMR to display tags, I then have to change the ICAO code in the vSMR toolbar.

Is it possible to get vSMR to have a mode to enable it to cover all of my airfields at once using one ASR?

Cheers,
Luke

**Comment by pierr3** [comment]
You can try and tweak the settings regarding filtering and change them to be so big they do not actually provide any filtering, you'll manly want to change "radar_range_nm". It's not a full fix but it should get you going.

**Comment by keanucz** [comment]
I'm curious as to how it's not a full fix, and also, maybe we could add a multiple airport mode..
