### ISSUE TITLE
vSMR causing Euroscope to crash

### ISSUE THREAD

**Issue by Mistadouf** [pierr3/vSMR#42]
When I click close in the Euroscope sector menu to close on an SMR radar screen, Euroscope immediately crashes. I've never had this issue with vSMR version 1.3.3. I'm using vSMR 1.4.0 and Euroscope 3.2a(r19).

**Comment by pierr3** [comment]
Thanks for the report, I'll try to have a look, but if anyone can it should be something to do with the EuroScopePlugInExit function in SMRPlugin.cpp

**Comment by pierr3** [comment]
Should be fixed in #46, feel free to message again if not
