### ISSUE TITLE
Is it possible to use vSMR without the tags?

### ISSUE THREAD

**Issue by 767Mark** [pierr3/vSMR#45]
I use CANSCOPE with Euroscope and would like to have the normal Canscope tags.  I have installed vSMR for the Hoppie CPDLC clearance system integration.  Is this possible?  If not is there another suggestion on how to use it in this way as above?  thanks.

**Comment by ghost** [comment]
Hey Mark,
You can enable vSMR and just have your regular ground view without the "SMR" tags by just creating a normal ASR. The departure list feature should still work.

**Comment by 767Mark** [comment]
Not quite sure how to do this.  I actually thought I had used an existing normal ASR and then added vSMR.

**Comment by aturneruk** [comment]
Yes! You can use the CPDLC part of vSMR independently of all the other functions. Simply load up your profile as normal, then load the vSMR plugin. Type .smr into the chat box and fill out the details. Once you're ready type .smr connect into the message box to sign on to the Hoppie network.

**Comment by pierr3** [comment]
@artturnip Is correct, this should be what you need! Let us know if not.
