### ISSUE TITLE
Feature Suggestion: Ability to do Hoppie ACARS CPDLC for Enroute controlling

### ISSUE THREAD

**Issue by sjames1066** [pierr3/vSMR#49]
Ability to issue Route directs, Level changes/instructions, speed/mach instructions, controller freq handoffs. 

Thanks in advance!

**Comment by pierr3** [comment]
Hey, this has been discussed before. I would love that but it is outside of the scope of this plugin so I do not want to implement, sorry :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
