### ISSUE TITLE
Aircraft shapes

### ISSUE THREAD

**Issue by ryana-0154** [pierr3/vSMR#5]
Hi,

Would it be possible to add in a feature where we could change the shape of the aircraft? Instead of it just being a big arrow, it'd make things a lot easier when it's busy!

Cheers!

**Comment by pierr3** [comment]
There is already a way to hide them in the menu, a way to edit them I won't do. But I'll make them prettier that's for sure.

**Comment by ryana-0154** [comment]
By editing I mean like the way there is built into euroscope, I'd much prefer something that isn't a little arrow!

**Comment by pierr3** [comment]
Yep, the plugin can't and doesn't use the EuroScope built-in editing feature, and if you want the little airplane that won't happen since it's unrealistic ;)

**Comment by ryana-0154** [comment]
I don't want the little aeroplane, just a filled dot would do! it's just the arrow is too big!

**Comment by pierr3** [comment]
I won't just put a filled dot, that's unrealistic. The arrow is not correct I agree, but for the size, it is actually the size of an aircraft, and it changes depending on the aircraft type, so the arrow isn't too big, it's actually the correct size ;)

**Comment by ryana-0154** [comment]
What shape for the aircraft are you thinking then?

**Comment by pierr3** [comment]
Take a look at the real world screenshots ;) 
http://community.vatsim-uk.co.uk/topic/29397-image-heathrow-smr-tags/

**Comment by ryana-0154** [comment]
Yep i'm happy with that! Are you thinking about those tags too?

**Comment by pierr3** [comment]
Those tags already where implemented in the dev build, check out the last commits !

**Comment by ryana-0154** [comment]
ah right!

**Comment by pierr3** [comment]
Nicer aircraft shapes have been introduced in b3d90d3b78804328dac0392a8ae36346d971f54d, we'll keep that for now, until someone starts yelling. Code by Lionel, cf credits.

**Comment by TheoBearman** [comment]
Screenshot?

**Comment by pierr3** [comment]
![New targets](https://www.dropbox.com/s/b17hm03rdp77c0m/2015-06-30_18-39-41.png?dl=1)
