### ISSUE TITLE
Re-evaluating use of tag menu popup functions

### ISSUE THREAD

**Issue by keanucz** [pierr3/vSMR#51]
There are some things like the `asid` tag item which correlate to a SID assignment menu, or the callsign tag item that correlates to the handoff menu and voice communication type menu.

Are these meant for people who disable the departure/arrival lists? Hearing from some people, I mostly hear that they miss the ability to draw the route line, so I'm considering replacing the callsign tag menu item with the route draw function. Or should we let users manually define what menus they want certain tag items to use?

**Comment by 1adamf** [comment]
Personally I don't think it would be particularly useful to be able to draw the route on the SMR. That's something that's more relevant to a radar view which I don't think the route would draw on while if you tried to draw the route from the SMR

**Comment by keanucz** [comment]
Fair enough, I'll scrap that then

**Comment by pierr3** [comment]
Yup, agree with @1adamf, this is an SMR, it should be used for anything else that ground control and hence route draw does not fit into that scope. The real world system also does not support a similar functionality (in the real world, route draw is surprisingly complex to implement).
