### ISSUE TITLE
Ability to change aircraft icon to default/something else??

### ISSUE THREAD

**Issue by keanucz** [pierr3/vSMR#53]
Was gathering feedback from a bunch of people in VATSIM UK, one of them dislikes the aircraft shapes and wants the ability to change it to either the default ES one or to something else. Is this possible??

**Comment by pierr3** [comment]
The aircraft shapes mimic the real word system as best as possible. They are not supposed to be generic shapes but primary radar returns. In the real world, some airports do not show the radar feedback, while some do. The current simulated returns are not very realistic in the sense that they are too airplane like. They look more like fancy potatoes than anything. Hence, we can improve the simulation of primary radar return, but won't switch to fake "shapes" to mimic the real system.

**Comment by keanucz** [comment]
Just looked at the NOVA's manual and realised that your aircraft shapes are actually accurate. I'll close this then.
