### ISSUE TITLE
Creating flight plans in pro mode

### ISSUE THREAD

**Issue by keanucz** [pierr3/vSMR#54]
I've come across a few aircraft that "book out", which basically means they want me to file a flightplan for them when they request it. But I have pro mode on, and since `.am` requires me to click on their tag, I cannot click on their tag, so I can only deal with filed ones. We'll have to make it so you can click on their aircraft symbol then?

**Comment by NathanInnes** [comment]
I might be late to the party... You need to click TARGET > ACQUIRE > Select aircraft. (SEE ATTACHED)
![image](https://user-images.githubusercontent.com/18389085/75913675-40be6880-5e4b-11ea-92d9-e56be670b749.png)


Then you will be able to set their flight plan up with F1+A or .am 

If not then let me know

**Comment by keanucz** [comment]
@NathanInnes I may be wrong but doesn't acquire assume the tag?

**Comment by NathanInnes** [comment]
I think it does, but it won't make much difference anyways if you're doing ground control. Once the aircraft has set the allocated squawk code you would release the aircraft.

**Comment by pierr3** [comment]
This is the incorrect procedure actually. When an aircraft with no flight plan calls up, you should open a new flightplan for them by using the .am CALLSIGN command, then assigning them a squawk. You would get their callsign when they call up. Once you give them the squawk, they will automatically be correlated and show up on your scope. TARGET -> Acquire does not assume a tag either.
