### ISSUE TITLE
Breaking backwards compatibility

### ISSUE THREAD

**Issue by LB767** [pierr3/vSMR#59]
When you add new settings to the json config file please either make it backwards compatible or make it very clear what gets broken.
I wasted an afternoon realising you need to specify push/taxi/depa tag colors otherwise it crashes :)
(I take full responsibility for being a noob, but still, could have saved some time there)

**Comment by keanucz** [comment]
Hrrm.. the only reason I'm guessing you had issues is because the new config file contains the ground status in the tag as well as custom defined ground status colours. So it is backwards compatible, but the new config file made it less so

**Comment by pierr3** [comment]
@Keanu73 Can you please check whether the current nightly config is compatible with the last release config?

**Comment by pierr3** [comment]
Closed as I tested this with no issues
