### ISSUE TITLE
Save Settings in RIMCAS and Approach Window

### ISSUE THREAD

**Issue by TheoBearman** [pierr3/vSMR#6]
Can we have the settings selected in the RIMAS menu and the approach window saved on close?

Can we also have the approach window opened on load if we had it open last time we closed Euroscope.

Thanks!

**Comment by pierr3** [comment]
Hi, normally, the approach window state (open/closed) is already saved. I'll work on the rest.

**Comment by TheoBearman** [comment]
Doesn't seem to be saving for me.

**Comment by pierr3** [comment]
@TheoBearman Can you try with EuroScope 3.2r2 beta? Download it here: http://euroscope.hu/installbeta/changes.html and tell me if it works.

**Comment by TheoBearman** [comment]
@pierr3 It's not saving in 3.2r2.

**Comment by pierr3** [comment]
I'm currently trying new saving methods, will see how that goes.

**Comment by pierr3** [comment]
Saving of the current airport has been fixed.
