### ISSUE TITLE
Polygon for closed runway

### ISSUE THREAD

**Issue by kusterjs** [pierr3/vSMR#62]
Polygons for closed runway should be able to be specified differently from the RIMCAS area, although this one is then actually deactived. This is because the RIMCAS area is usually larger than the runway surface, but you don't want more red on your screen than necessary and also see things like intersections properly.

**Comment by keanucz** [comment]
This is possible if you define the runway coordinates as per the example config file.

**Comment by pierr3** [comment]
You're right, RIMCAS should always use a calculated runway area, and not the actual definition of the Runway, that could be changed in [SMRRadar.cpp line 1705](https://github.com/pierr3/vSMR/blob/c8c513e8e9d6195e5fde14a9439b959f80b4b337/vSMR/SMRRadar.cpp#L1705) where only the calculated runway area should be passed to RIMCAS and the definition from the config ignored.

**Comment by pierr3** [comment]
Pushing this, could you give it a try @kusterjs on the next nightly ?
