### ISSUE TITLE
Ability to hide tags

### ISSUE THREAD

**Issue by keanucz** [pierr3/vSMR#63]
Sometimes even with pro mode on a lot of tags can make a mess of the airport. My idea is when you right-click on the blank space of the tag, it will hide it, and right clicking on the aircraft icon will show their tag again.

**Comment by pierr3** [comment]
This should not be a feature. By design ATM systems do not allow you to hide tags that can be relevant to you, and manually being able to disregard tags would lead to lack of awareness.
