### ISSUE TITLE
FAOR tags not showing

### ISSUE THREAD

**Issue by phoenixegmh** [pierr3/vSMR#65]
With vSMR running at FAOR (old code FAJS), no tags show. Have used FACT and shows OK, is this a problem because of the ICAO code change?

**Comment by pierr3** [comment]
It's likely, but this is a sector file problem, not a vSMR one. If your sector definition has the correct coordinates for FAOR, it'll work fine. it sounds like your sector file needs to be updated.

**Comment by phoenixegmh** [comment]
Just looking at the sector file now and FAOR appears to be in there correctly. It has co-ordinates and they appear correct

**Comment by phoenixegmh** [comment]
Airport is defined under AIRPORT section in the .sct file as:

FAOR 000.000 S026.08.01.298 E028.14.32.341 D

**Comment by kusterjs** [comment]
Maybe an issue with the altitude filter for ground traffic? FAOR is known for this since it is above the default value of 5000 ft.

**Comment by phoenixegmh** [comment]
> Maybe an issue with the altitude filter for ground traffic? FAOR is known for this since it is above the default value of 5000 ft.

Negative, options adjusted for 5600ft and it doesn't show any airborne tags either

**Comment by pierr3** [comment]
I see the elevation of FAOR ASML is 5558ft, try to raise the altitude filter to at least 7000ft and see what happens.

**Comment by phoenixegmh** [comment]
Raised to 7000ft, still nothing showing (AC on Stand A1 in the attached)
![image](https://user-images.githubusercontent.com/62211163/76706358-c0b3c080-66de-11ea-87c5-1f4576ee6e84.png)

**Comment by phoenixegmh** [comment]
I think we could be onto something with the AD elevation though, I've just tried FALA and that didn't work. Awaiting further testing at FYWH to see if that clarifies the issue as it has a similar elevation.

**Comment by pierr3** [comment]
There is the problem ;) You need to change the altitude filter in the config file (see https://github.com/pierr3/vSMR/wiki/Editing-the-Plugin-Settings-(.json-file)#changing-the-settings-values-in-a-profile), changing it in the EuroScope dialog will change nothing as it does not communicate with the plugin.

**Comment by phoenixegmh** [comment]
That's got it! Perfect, thanks!
