### ISSUE TITLE
No grey menu bar after following the instructions.

### ISSUE THREAD

**Issue by ItayFishman** [pierr3/vSMR#66]
Hello, I am trying to use vSMR for LLBG ground and after I loaded the plugin, edited the ASR file and loaded the sector, the gray menu bar won't show up. 
Also when I connect to the network I can't see the aircraft on the radar after I edit the ASR file.
What should be done in order to fix this issue?

**Comment by pierr3** [comment]
Hey there, have another good look at the config and ensure the plugin is properly loaded. Edit your file while EuroScope is not running, then open EuroScope, guarantee you it's a user config error :)
