### ISSUE TITLE
Measuring shortcut disabled in vSMR ASR files

### ISSUE THREAD

**Issue by githubvatsim** [pierr3/vSMR#67]
In non-vSMR ASR files, it is possible to double-click and drag to measure distance and display reciprocal headings. This does not seem to work in ASR files configured for the plugin.
[ASRfiles.zip](https://github.com/pierr3/vSMR/files/4489805/ASRfiles.zip)

**Comment by pierr3** [comment]
This is a limitation of EuroScope, not possible to enable this without enabling other radar drawings. That's why there is a custom measure too.

**Comment by githubvatsim** [comment]
Thanks for the very quick response.

Yes, I see that feature for aircraft in flight. In a perfect world, we could measure runway remaining for intersection departures.

Stay safe….Tony



On Apr 16, 2020, at 17:32, Pierre Ferran <notifications@github.com> wrote:


This is a limitation of EuroScope, not possible to enable this without enabling other radar drawings. That's why there is a custom measure too.

**Comment by pierr3** [comment]
You can! From the Display Menu Select QDR Select Reference, then click two points on your screen and you will have a distance!

See also here: https://github.com/pierr3/vSMR/wiki/Menu-Bar

**Comment by githubvatsim** [comment]
Excellent.

Thanks very much for your work on this project.

T.

-----------------
Tony Koch
416.423.7824

On Apr 16, 2020, at 18:29, Pierre Ferran <notifications@github.com> wrote:


You can! From the Display Menu Select QDR Select Reference, then click two points on your screen and you will have a distance!

See also here: https://github.com/pierr3/vSMR/wiki/Menu-Bar <https://github.com/pierr3/vSMR/wiki/Menu-Bar>

**Comment by githubvatsim** [comment]
I see at https://github.com/pierr3/vSMR/wiki/Editing-the-Plugin-Settings-%28.json-file%29 <https://github.com/pierr3/vSMR/wiki/Editing-the-Plugin-Settings-(.json-file)> that there is no option to display distance in feet instead of meters. This would be a nice feature in future.

T.




Excellent.

Thanks very much for your work on this project.

T.

-----------------
Tony Koch
416.423.7824

On Apr 16, 2020, at 18:29, Pierre Ferran <notifications@github.com <mailto:notifications@github.com>> wrote:


You can! From the Display Menu Select QDR Select Reference, then click two points on your screen and you will have a distance!

See also here: https://github.com/pierr3/vSMR/wiki/Menu-Bar <https://github.com/pierr3/vSMR/wiki/Menu-Bar>
