### ISSUE TITLE
Output for Occupied CPDLC Callsign

### ISSUE THREAD

**Issue by TheoBearman** [pierr3/vSMR#74]
When trying to use the `.smr connect` command to login to a preset callsign which another user has already logged in to the Hoppie network with, no output is observed. Suggest creating a text message in ES in these instances to alert the user to this.

**Comment by pierr3** [comment]
Give it a try on the nightly, should be fixed

**Comment by TheoBearman** [comment]
Tested this in the live environment with the nightly. Works perfectly. Thanks!
