### ISSUE TITLE
Afterglow setting does not get saved.

### ISSUE THREAD

**Issue by redac** [pierr3/vSMR#76]
### Afterglow
![ES](https://i.imgur.com/8E0HLrQ.png)
It appears that the afterglow setting does not get saved, thus it auto reverts to ON each time you turn it OFF and restart ES.

**Comment by hpeter2** [comment]
@pierr3 Hi Pierre,
can you quickly explain commit [2c1d206](https://github.com/pierr3/vSMR/commit/2c1d206037e7cc83aa3913ef61df5b5befc3fece) ? 
I tried to debug this Issue, but just didn't get this method called by EuroScope. A revert of mentioned commit doesn't crash EuroScope with latest version 3.2.1.25.

**Comment by pierr3** [comment]
@redac is this behaviour still occuring on the latest nightly?
@hpeter2 I thought that calling this function on destruction did cause a crash, if it did not my bad, no specific reason, it was part of the exploratory excercise to fix the crash issue

**Comment by migte** [comment]
Hello. 

I am also experiencing this issue. The afterglow option (as well as all of the other options) do not save between sessions, I'm currently running the nightly build - originally the stable one but I read the message above and figured it may have been a solution. Neither work.

**Comment by migte** [comment]
In fact, none of the options save. I'll make a new issue then as the problem is more broad than just the afterglow. 

Edit; Solved in another issue
