### ISSUE TITLE
Release notes missing in binary release packages

### ISSUE THREAD

**Issue by droesen** [pierr3/vSMR#78]
Hi,

please include release notes text file in the binary download ZIP file
(ideally with complete history of older versions too). Thanks!

Best regards,
Daniel

**Comment by hpeter2** [comment]
A draft in attachments, if wanted.
[release-notes-draft.txt](https://github.com/pierr3/vSMR/files/5171524/release-notes-draft.txt)

**Comment by droesen** [comment]
That looks excellent to me!

**Comment by pierr3** [comment]
Thanks for this, the release note are listed in the "https://github.com/pierr3/vSMR/releases" page as well as in the commit messages. I want to avoid duplication of information and increased maintenance, hence I would rather not have that file with the DLL. Let me know what you think.

**Comment by pierr3** [comment]
Will be kept in commit list / release page
