### ISSUE TITLE
DLL version file header not updated

### ISSUE THREAD

**Issue by droesen** [pierr3/vSMR#79]
Hi,

I've noticed that the "version" tag of the DLL is not being set
to the actual version. For example, the current v1.5 DLL is
tagged as 1.2.0.0, whereas the version I have installed (that
identifies itself in ES Plugin dialog as "RC2-dev-e32", whatever
that means) claims to be 1.0.0.1, which I cannot find in GitHub
project tag list.

Stumbled over that problem when seeing the v1.5 release announcement
and wanted to check the feature/changes delta between the release
I got from my vACC as part of a starter plugin/config bundle, and
the new v1.5 - and found myself struggling to find out which version
I actually have installed ("1.0.0.1" / "RC2-dev-e32").

Is there any way to make sure that the release version/tag,
DLL version file header tag and the ES plugin dialog version tag
remain in sync via the build/release workflow?

BTW, thanks for your nice work, very much appreciated!

Best regards,
Daniel

**Comment by hpeter2** [comment]
Please note that the version you mentioned is 5 years old from [pre-release v1.2.0-beta.1](https://github.com/pierr3/vSMR/releases/tag/v1.2.0-beta.1) of Jul 5, 2015.

---

The issue mentioned is still a Bug inside the current [vSMR.rc file](https://github.com/pierr3/vSMR/blob/master/vSMR/vSMR.rc). 
The _"FileVersion"_ and _"ProductVersion"_ should be updated to current build version 1.5-102. _"@appveyor_build"_ might be possible.

**Comment by droesen** [comment]
> Please note that the version you mentioned is 5 years old from [pre-release v1.2.0-beta.1](https://github.com/pierr3/vSMR/releases/tag/v1.2.0-beta.1) of Jul 5, 2015.

Well that is the version provided by my VACC NAV department in their ES starter kit. :-) I was in the process of upgrading, trying to find out the changes between the version I have installed and your 1.5 release to make sure nothing breaks (or what config needs changing etc.). This is where I ran in those versioning issues.

> The issue mentioned is still a Bug inside the current [vSMR.rc file](https://github.com/pierr3/vSMR/blob/master/vSMR/vSMR.rc).
> The _"FileVersion"_ and _"ProductVersion"_ should be updated to current build version 1.5-102.

Also, FILEVERSION and PRODUCTVERSION which are both set to 1,2,0,0.

**Comment by pierr3** [comment]
Indeed, this I need to update, but @droesen the leading version you should check is the version displayed in the EuroScope Plugin dialog. Indeed RC2-dev-e32 is so old it does not even have a version yet (RC2 stands for Release Candidate 2), so that file was not even in the versioning system used now. The plugin now uses https://semver.org/, to display compatibility with versions.

I will update the resource file to include the proper version :)

**Comment by pierr3** [comment]
Fixed in latest commit
