### ISSUE TITLE
No FPL in Departure List

### ISSUE THREAD

**Issue by Iwhite67** [pierr3/vSMR#86]
Hello, with aircraft who don't disconnect and send a new flight plan, he don't come into Departure list.

After disconnect and reconnect is good.

Maybe vSMR ? this problem is not only me but other ATC have this problem

**Comment by kusterjs** [comment]
There is no specific departure list for vSMR. Verify if you can observe the same also on a non-vSMR display. I would assume this is the case. And as a result this issue is not related to vSMR.

**Comment by Iwhite67** [comment]
so, is a issue related from euroscope
