### ISSUE TITLE
How to tell if an aircraft is squawking mode Charlie or not?

### ISSUE THREAD

**Issue by migte** [pierr3/vSMR#88]
What would be the way for me to verify a user is on mode C? I can't find any identifiers within the scope.

**Comment by kusterjs** [comment]
https://github.com/pierr3/vSMR/wiki/Approach-window

**Comment by migte** [comment]
Well this doesn't really help me because I am running ground at an airport that utilizes ASDE-X on all taxiways as ground. (So mode C.)

Someone mentioned to me a diamond and X symbol over the yellow aircraft. I haven't had the chance but I was going to check that out later to see what that symbology stood. Will report back.

**Comment by migte** [comment]
Ok, so there is obviously no documentation on what the specific symbols mean, but I find that a diamond over an aircraft means mode C. As a suggestion to the developer, this is extremely hard to see on heavy aircraft due to their larger size on the scope and the contrast of the colors (although it is just fine on normal sized aircraft.) Could this possibly be enlarged?

**Comment by LeoChen98** [comment]
it might be more obvious to set another color for those mode C aircraft?

**Comment by migte** [comment]
Something like that, or perhaps just enlarge the current diamond to be visible on heavy aircraft rather than being the same size. I can't quite understand how this application is laid out (nor do I speak this language) so I don't know how difficult it would be to do something like that.
