### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by hazzas-99** [pierr3/vSMR#9]
This is clearly an enhancement, that if you can achieve, I'd be most impressed with!

Virtual Controller Assistant currently contains a countdown timer to assist with departure separation, but I was wondering whether vSMR could provide the same. This could be in two ways:
- A countdown timer that you can place somewhere around the screen (it should also save the location of the timer upon closing EuroScope - VCA doesn't do that with ES3.2)
- Some sort of visual that shows time since departure - perhaps vSMR can measure the time that the aircraft starts climbing, and then show that somewhere? Maybe in a list?

**Comment by pierr3** [comment]
Okay, thanks for ideas. I'll implement a smart countdown timer to sequence departures, i'm affraid I won't be able to code something that can mesure when an aircraft starts climbing, i'm not that amazing :stuck_out_tongue_closed_eyes:

**Comment by pierr3** [comment]
Will not add.
