### ISSUE TITLE
no vSMR options save between sessions.

### ISSUE THREAD

**Issue by migte** [pierr3/vSMR#95]
No options found in Euroscope such as the SRW screens, Label Font Size, Afterglow, GRND Trail Dots,, and so on save between sessions. This makes it annoying to have to re do the configuration every time you load up Euroscope.

**Comment by migte** [comment]
Note - the issue remains - but I found a temporary workaround for some of the options in the .asr file. I just wrote in some definitions as found in SMRRadar.cpp for them to load when I open the file. Still doesn't save though.

**Comment by pierr3** [comment]
This is a common EuroScope bug. The first time you load or create a new vSMR ASR, you need to force the saving by selecting Open SCT -> Save ASR then Open SCT -> Close ASR and hit save in the dialog. After that, changes should pop up every time you close the ASR in the normal manner.

**Comment by migte** [comment]
That worked, thanks!
