### ISSUE TITLE
Pop up information feature  request

### ISSUE THREAD

**Issue by KingSpidey101** [pierr3/vSMR#96]
Can there be a feature where initially only the callsign shows up in the tag and when we hover over that tag as and when required, the rest information would be displayed.
This can help reduce the space taken by the tags without compromising the information included within it.

**Comment by pierr3** [comment]
That's not a feature of the real system and hence there is no plan to implement unfortunately. The nature of the ground display also means you should have as much as possible without interaction. Your main working space is the departure list or a strip system for example.
